// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<Forestry:factory:2>);
recipes.remove(<Forestry:factory:1>);
recipes.remove(<Forestry:factory>);
recipes.remove(<Forestry:core>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<Forestry:factory:2>, [[<ore:Steel>, <ore:blockGlassColorless>, <ore:Steel>], [<ore:AdvancedAlloy>, <Forestry:sturdyMachine>, <ore:AdvancedAlloy>], [<ore:Steel>, <hbm:item.centrifuge_element>, <ore:Steel>]]);
recipes.addShaped(<Forestry:factory:1>, [[<ore:Steel>, <minecraft:glass>, <ore:Steel>], [<ore:AdvancedAlloy>, <Forestry:sturdyMachine>, <ore:AdvancedAlloy>], [<ore:Steel>, <hbm:item.part_generic>, <ore:Steel>]]);
recipes.addShaped(<Forestry:factory>, [[<hbm:item.fluid_tank_empty>, <hbm:item.ingot_steel>, <hbm:item.fluid_tank_empty>], [<minecraft:glass>, <Forestry:sturdyMachine>, <minecraft:glass>], [<hbm:item.fluid_tank_empty>, <hbm:item.ingot_steel>, <hbm:item.fluid_tank_empty>]]);
recipes.addShaped(<Forestry:core>, [[<ore:Steel>, <Forestry:flutterlyzer>, <ore:Steel>], [<hbm:item.circuit:11>, <Forestry:sturdyMachine>, <hbm:item.circuit:11>], [<ore:Steel>, <hbm:item.tank_steel>, <hbm:item.ingot_steel>]]);
recipes.addShaped(<Forestry:core>, [[<ore:Steel>, <Forestry:treealyzer>, <ore:Steel>], [<hbm:item.circuit:11>, <Forestry:sturdyMachine>, <hbm:item.circuit:11>], [<ore:Steel>, <hbm:item.tank_steel>, <hbm:item.ingot_steel>]]);
recipes.addShaped(<Forestry:core>, [[<ore:Steel>, <Forestry:beealyzer>, <ore:Steel>], [<hbm:item.circuit:11>, <Forestry:sturdyMachine>, <hbm:item.circuit:11>], [<ore:Steel>, <hbm:item.tank_steel>, <hbm:item.ingot_steel>]]);

